# Generated by Django 5.2.6 on 2025-09-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('curso', models.CharField(max_length=40)),
                ('rgm', models.IntegerField(unique=True)),
                ('semestre', models.IntegerField()),
            ],
        ),
    ]
